### ISSUE TITLE
i2c5 routed to incorrect DC-SCI pins, PCIe signals off-by-two

### ISSUE THREAD

**Issue by jk-ozlabs** [antmicro/artix-dc-scm#1]
Firstly, thanks for the design! I really appreciate having the schematics and board layout open.

I'm having an issue with I2C5. In the DC-SCI spec, pins A11 and A12 are intended for I2C5:

![20220923_11h48m32s_grim](https://user-images.githubusercontent.com/8000933/191888884-1b4826fe-bc40-4c22-aaa2-f5c3956ba31d.png)

However, the schematic has A11 grounded, and A12 connected to `PCIE_BMC_CLK_100_P` instead, and I2C5 is placed after the three differential pairs of PCIe signals:

![20220923_11h50m02s_grim](https://user-images.githubusercontent.com/8000933/191889091-a261176d-8d1f-4f9d-9223-c6359b5e65c2.png)

It looks like the I2C5 pins are just on the wrong side of the PCIe set, and the PCIe signals should be shifted up by two.

We can work-around SDA in gateware, but SCL being grounded makes the i2c bus unusable without a hardware rework.

We're not using PCIe here, but this would also cause issues for those who might be.

**Comment by jk-ozlabs** [comment]
Actually, I don't think we can't work-around SDA in gateware - that PCIe IO is pulling the line down to 1.8V.

**Comment by pkatarzynski** [comment]
Hi jk-ozlabs

Thank you for your update - we will cross-check and update if needed.

**Comment by jk-ozlabs** [comment]
Thanks @pkatarzynski ! I have a few other things to feedback on the design - mainly just enhancements. Would those be useful at all? (ie., are you planning to do another revision of this board in future?)

**Comment by pkatarzynski** [comment]
Indeed there was a glitch in signal assignment. We have pushed a fix to that. Thank you for spotting this. 

Actually we are doing quite a lot around BMC and server integration -  if you have any questions or suggestions, please shoot us an email using contact@antmicro.com
